version: "3.7"

services:
  web:
    build: .
    command: sh -c "npm start"
    working_dir: /app
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE: broadcast_db
      DB_PORT: 5432
      # FAKETIME: "@2021-12-10 20:59:40"
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
  jobs:
    build: .
    command: sh -c "node bree"
    working_dir: /app
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE: broadcast_db
      DB_PORT: 5432
      # FAKETIME: "@2021-12-10 20:59:40"
      HOOKBIN_URL: https://hookb.in/Px0LW2peW0TpKPrrKWgl
    volumes:
      - "./:/app"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine3.15
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: broadcast_db 
    ports:
      - "5432:5432"

volumes:
  pgdata:
  pgconf:
  pglog: 
