version: "3.7"

services:
  web:
    build: .
    command: sh -c "npm start"
    working_dir: /app
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE: broadcast_db
      DB_PORT: 5432
      # FAKETIME: "@2021-12-13 21:59:40"
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    restart: 'unless-stopped'
    depends_on:
      - db
  jobs:
    build: .
    command: sh -c "node bree"
    working_dir: /app
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE: broadcast_db
      DB_PORT: 5432
      # FAKETIME: "@2021-12-13 21:59:40"
      HOOKBIN_URL: https://hookb.in/2qKG7ZeqmBSdzq88zKd2
      # HOOKBIN_URL: https://ennc8lpshe6.x.pipedream.net
      # HOOKBIN_URL: https://webhook.site/ef2b8e0e-33ea-409a-b96d-e4797b49538f
    volumes:
      - "./:/app"
    restart: 'unless-stopped'
    depends_on:
      - db
  db:
    build: 
      context: .
      dockerfile: Dockerfile.pg
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: broadcast_db 
      # FAKETIME: "@2021-12-13 21:59:40"
      # FAKETIME: "@2021-12-13 22:00:00"\
    restart: 'unless-stopped'
    ports:
      - "5432:5432"

volumes:
  pgdata:
  pgconf:
  pglog: 
